version: "3.9"
services:
#  server:
#    build: /server
#    ports:
#      - "8080:8080"
  mysql:
    image: "mysql:8.0.29"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "3306:3306"  # host物理直接映射端口为3306
    environment:
      MYSQL_DATABASE: "db" # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: "pass" # root管理员用户密码
